/* eslint-disable no-console */
/* eslint-disable no-plusplus */
const products = [
  {
    _id: '3d7e9c33-0080-4bd2-b2bf-56552da31e35',
    qty: 0,
    name: 'Ardor Avaitor',
    description:
          'Discover the dynamic and masculine style of the Ardor Aviator sunglasses by Ray-Ban. Perfect for the modern man who seeks adventure, these shades offer a bold look thats ideal for outdoor activities. The sleek design and superior UV protection make them a must-have for every sports enthusiast. Embrace the Ray-Ban brand and elevate your sports gear with these Aviator sunglasses.',
    brand: 'Ray-Ban',
    category: 'Sports',
    gender: 'Men',
    weight: '200g',
    quantity: 10,
    image: 'sports1',
    rating: 4.5,
    price: 1999,
    newPrice: 1899,
    trending: true,
  },
  {
    _id: '887cdd99-1503-4527-aef4-88c521126a47',
    qty: 0,
    name: 'Caper Active',
    description:
          'Elevate your active lifestyle with the Caper Active sunglasses from Persol. Designed for the modern man who embraces challenges, these shades provide a sporty edge that complements any adventure. The lightweight build and UV protection make them a reliable choice for outdoor enthusiasts. Embrace the Persol brand and enhance your sports gear with these Active sunglasses.',
    brand: 'Persol',
    category: 'Sports',
    gender: 'Men',
    weight: '100g',
    quantity: 5,
    image: 'sports2',
    rating: 4.8,
    price: 1299,
    newPrice: 1199,
    trending: true,
  },
  {
    _id: 'dc2b2495-eb6c-4889-a6f7-3c8853a01ba2',
    qty: 0,
    name: 'Alder Street',
    description:
          'Experience style and versatility with the Alder Street sunglasses from Kate Spade. Designed for those who appreciate unisex fashion, these shades offer a blend of functionality and elegance. The durable construction and UV protection make them a reliable choice for various outdoor activities. Embrace the Kate Spade brand and elevate your sports gear with these Street sunglasses.',
    brand: 'Kate Spade',
    category: 'Sports',
    gender: 'Unisex',
    weight: '750g',
    quantity: 15,
    image: 'sports3',
    rating: 4.7,
    price: 2999,
    newPrice: 2000,
    trending: true,
  },
  {
    _id: 'fd25068a-9647-45ba-b44d-c8af1523148a',
    qty: 0,
    name: 'Corral Round',
    description:
          'Elevate your outdoor style with the Corral Round sunglasses from Carrera. Designed for the contemporary individual who seeks both fashion and function, these shades offer a classic round shape thats perfect for any occasion. The robust build and UV protection make them an ideal choice for outdoor pursuits. Embrace the Carrera brand and enhance your sports gear with these Round sunglasses.',
    brand: 'Carrera',
    category: 'Sports',
    gender: 'Unisex',
    weight: '300g',
    quantity: 8,
    image: 'sports4',
    rating: 3.8,
    price: 2499,
    newPrice: 2300,
  },
  {
    _id: 'fcd7e3a2-80f9-47d1-9e34-6a40e5f684a1',
    qty: 15,
    name: 'Athletic Shades',
    description:
          'Gear up for intense outdoor activities with the Athletic Shades sunglasses by SportX. Engineered for performance, these shades provide optimal UV protection and enhanced clarity. The lightweight and durable design ensures they stay put during your most rigorous adventures. Elevate your sports experience with these high-performance sunglasses.',
    brand: 'SportX',
    category: 'Sunglasses',
    gender: 'Unisex',
    weight: '90g',
    quantity: 25,
    image: 'sports5',
    rating: 4.9,
    price: 2499,
    newPrice: 1999,
    trending: true,
  },
  {
    _id: '95cd381c-32cf-46e5-8a75-05d30a421d6b',
    qty: 0,
    name: 'Hyperclax Active',
    description:
          'Unleash your active spirit with the Hyperclax Active sunglasses from Oakley. Designed for the modern woman who embraces outdoor challenges, these shades provide a blend of style and functionality. The robust construction and UV protection make them a reliable choice for various activities. Embrace the Oakley brand and enhance your sports gear with these Active sunglasses.',
    brand: 'Oakley',
    category: 'Sports',
    gender: 'Women',
    weight: '900g',
    quantity: 3,
    image: 'sports6',
    rating: 3.5,
    price: 3999,
    newPrice: 3500,
  },
  {
    _id: '6c800171-bea6-4cb2-811d-7c419a59dcb8',
    qty: 0,
    name: 'Hip Hop Candy',
    description:
          'Experience the bold and dynamic style of the Hip Hop Candy sunglasses by Kate Spade. Designed for the modern man who wants to stand out, these shades offer a fresh and unique look that complements your active lifestyle. The robust design and reliable UV protection make them the perfect choice for outdoor adventures. Embrace the Kate Spade brand and enhance your sports gear with these Candy sunglasses.',
    brand: 'Kate Spade',
    category: 'Sports',
    gender: 'Men',
    weight: '400g',
    quantity: 6,
    image: 'sports7',
    rating: 4.1,
    price: 1499,
    newPrice: 1399,
    trending: true,
  },
  {
    _id: '9ca598d9-7cb5-4fb0-8455-b43028f9cb96',
    qty: 0,
    name: 'Punk Cut Out',
    description:
          'Unleash your inner rebel with the Punk Cut Out sunglasses from Ray-Ban. Designed for women who dare to stand out, these shades feature a unique cut-out design that adds an edgy twist to any outfit. The lightweight construction ensures all-day comfort, while the UV-protective lenses keep your eyes safe from the sun\'s rays. Embrace the punk spirit and make a bold statement wherever you go.',
    brand: 'Ray-Ban',
    category: 'Sports',
    gender: 'Women',
    weight: '102g',
    quantity: 9,
    image: 'sports8',
    rating: 4.3,
    price: 2999,
    newPrice: 2599,
    trending: true,
  },
  {
    _id: '9e3419eb-e5f6-4813-8bf4-6d72b6498235',
    qty: 0,
    name: 'Blue Ray Wayfarer',
    description:
          'Experience timeless elegance with the Blue Ray Wayfarer sunglasses by Carrera. Designed for those who appreciate unisex fashion, these shades offer a blend of sophistication and style. The high-quality materials ensure durability and comfort, while the lenses provide optimal UV protection. Elevate your look with these exquisite sunglasses that exude charm and grace.',
    brand: 'Carrera',
    category: 'Sports',
    gender: 'Unisex',
    weight: '550g',
    quantity: 7,
    image: 'sports9',
    rating: 4.8,
    price: 4999,
    newPrice: 4000,
  },
  {
    _id: 'a84d980e-cf9e-4607-b74d-68f7a1c45771',
    qty: 0,
    name: 'Full rim acetate black',
    description:
          'Elevate your optical experience with the Full Rim Acetate Black glasses from Ray-Ban. Designed for the modern man who values style and vision, these glasses offer a classic design that complements any look. The high-quality materials and precision construction ensure comfort and durability. Enhance your vision with these versatile and stylish glasses.',
    brand: 'Ray-Ban',
    category: 'Vision',
    gender: 'Men',
    weight: '200g',
    quantity: 10,
    image: 'vision1',
    rating: 4.5,
    price: 1999,
    newPrice: 1900,
  },
  {
    _id: '51db0e19-b0e0-4d6e-bce0-739f1bd37ba7',
    qty: 0,
    name: 'Rounded Gold',
    description:
          'Embrace luxury and sophistication with the Rounded Gold glasses by Persol. Crafted for the modern man with a refined taste, these glasses offer a blend of timeless style and impeccable quality. The intricate details and premium materials ensure a comfortable and elegant fit. Elevate your look with these exquisite glasses that exude charm and class.',
    brand: 'Persol',
    category: 'Vision',
    gender: 'Men',
    weight: '190g',
    quantity: 5,
    image: 'vision2',
    rating: 2.8,
    price: 1299,
    newPrice: 1000,
    trending: true,
  },
  {
    _id: '35332c85-f853-407a-80f8-840069381a0d',
    qty: 0,
    name: 'Jungle Safari',
    description:
          'Experience the thrill of exploration with the Jungle Safari glasses from Kate Spade. Designed for those who appreciate unisex fashion and adventure, these glasses offer a unique blend of style and functionality. The high-quality materials and thoughtful design ensure comfort and durability. Enhance your vision with these versatile and fashionable glasses.',
    brand: 'Kate Spade',
    category: 'Vision',
    gender: 'Unisex',
    weight: '750g',
    quantity: 15,
    image: 'vision3',
    rating: 4.7,
    price: 2999,
    newPrice: 2899,
  },
  {
    _id: '440cec02-21e1-4447-bdd9-d51482b7ce4b',
    qty: 0,
    name: 'Airway Black',
    description:
          'Step into modernity with the Airway Black glasses from Carrera. Designed for the contemporary individual who seeks both style and vision, these glasses offer a sleek design thats perfect for any occasion. The high-quality materials and precision construction ensure a comfortable fit and lasting quality. Enhance your vision with these versatile and stylish glasses.',
    brand: 'Carrera',
    category: 'Vision',
    gender: 'Unisex',
    weight: '300g',
    quantity: 8,
    image: 'vision4',
    rating: 3.8,
    price: 2499,
    newPrice: 1499,
  },
  {
    _id: '77f519a8-a40f-443d-8c9e-5314b24cf06d',
    qty: 0,
    name: 'Cat-eyed Gold',
    description:
          'Experience elegance and flair with the Cat-eyed Gold glasses by Oakley. Designed for the modern woman who values both style and vision, these glasses offer a unique cat-eye shape thats perfect for any occasion. The high-quality materials and precision construction ensure comfort and lasting quality. Elevate your vision with these versatile and fashionable glasses.',
    brand: 'Oakley',
    category: 'Vision',
    gender: 'Women',
    weight: '900g',
    quantity: 3,
    image: 'vision5',
    rating: 3.5,
    price: 3999,
    newPrice: 3790,
  },
  {
    _id: '11a2bfb4-2acf-40da-a12f-60dfcce8ed95',
    qty: 0,
    name: 'Full Rim Steel Gray',
    description:
          'Step into sophistication with the Full Rim Steel Gray glasses by Kate Spade. Designed for the modern man who values both style and vision, these glasses offer a classic full rim design thats versatile and timeless. The high-quality materials and precise construction ensure comfort and lasting quality. Elevate your vision with these stylish and functional glasses.',
    brand: 'Kate Spade',
    category: 'Vision',
    gender: 'Men',
    weight: '400g',
    quantity: 6,
    image: 'vision6',
    rating: 4.1,
    price: 1499,
    newPrice: 1459,
  },
  {
    _id: '6033723f-a8db-4ad8-bfda-d191778141aa',
    qty: 0,
    name: 'Rose Gold Chase',
    description:
          'Discover elegance and style with the Rose Gold Chase glasses by Ray-Ban. Designed for the modern woman who values both fashion and vision, these glasses offer a sleek and timeless look that complements any outfit. The high-quality materials and precision construction ensure comfort and lasting quality. Elevate your vision with these exquisite and versatile glasses.',
    brand: 'Ray-Ban',
    category: 'Vision',
    gender: 'Women',
    weight: '120g',
    quantity: 9,
    image: 'vision7',
    rating: 4.3,
    price: 2999,
    newPrice: 2599,
  },
  {
    _id: 'ac072970-8dac-42fe-8c31-a8fa6fd4b64a',
    qty: 0,
    name: 'Full Rim Airflex',
    description:
          'Elevate your optical experience with the Full Rim Airflex glasses by Carrera. Designed for those who appreciate both style and function, these glasses offer a blend of modern design and reliable vision. The high-quality materials and precision construction ensure comfort and lasting quality. Elevate your vision with these versatile and fashionable glasses.',
    brand: 'Carrera',
    category: 'Vision',
    gender: 'Unisex',
    weight: '550g',
    quantity: 7,
    image: 'vision8',
    rating: 4.8,
    price: 4999,
    newPrice: 3999,
  },
  {
    _id: '8ad38385-1211-4192-8108-db851b4e9434',
    qty: 0,
    name: 'Mercury Rounded Red',
    description:
          'Step into sophistication with the Mercury Rounded Red glasses by Carrera. Designed for the contemporary individual who values both style and vision, these glasses offer a unique rounded shape thats perfect for any occasion. The high-quality materials and precision construction ensure comfort and lasting quality. Elevate your vision with these versatile and stylish glasses.',
    brand: 'Carrera',
    category: 'Vision',
    gender: 'Unisex',
    weight: '550g',
    quantity: 7,
    image: 'vision9',
    rating: 4.8,
    price: 4999,
  },
  {
    _id: 'c4b9e2f6-3ac0-4d85-a0ce-9e4f2d1b0b28',
    qty: 12,
    name: 'Futuristic Shades',
    description: 'Step into the future with the Futuristic Shades sunglasses.These cutting-edge sunglasses feature a modern and sleek design thats perfect for trendsetters. The advanced materials offer durability and a lightweight feel, while the high-tech lenses provide superior UV protection and visual clarity. Embrace innovation with these modern sunglasses.',
    category: 'Sunglasses',
    gender: 'Unisex',
    weight: '95g',
    quantity: 18,
    image: 'sun1',
    rating: 4.5,
    price: 3799,
    newPrice: 3299,
    trending: true,
  },
  {
    _id: '53ca5f50-39f4-4c77-be14-c3246cfc5dc6',
    qty: 0,
    name: 'Burgas',
    description:
          'Step into elegance and sophistication with the Burgas sunglasses by Carrera. Designed for the modern woman who values both style and vision, these sunglasses offer a timeless and versatile look that complements any outfit. The high-quality materials and precise construction ensure comfort and lasting quality. Elevate your style with these exquisite and fashionable sunglasses.',
    brand: 'Carrera',
    category: 'Sunglasses',
    gender: 'Women',
    weight: '550g',
    quantity: 7,
    image: 'sun2',
    rating: 4.8,
    price: 4999,
    newPrice: 4700,
  },
  {
    _id: 'c6dcde20-2e9f-470c-b76c-38b01ab7e16e',
    qty: 0,
    name: 'Candyfloss-302',
    description:
          'Elevate your style with the Candyfloss-302 sunglasses by Ray-Ban. Designed for the modern man who values both fashion and function, these sunglasses offer a classic and versatile design that complements any look. The high-quality materials and precision construction ensure comfort and lasting quality. Elevate your style with these stylish and functional sunglasses.',
    brand: 'Ray-Ban',
    category: 'Sunglasses',
    gender: 'Men',
    weight: '200g',
    quantity: 10,
    image: 'sun3',
    rating: 4.5,
    price: 1999,
    newPrice: 1899,
  },
  {
    _id: 'c76b3840-47d2-4d38-b465-af68e2af9dcd',
    qty: 0,
    name: 'Phenomenal Mercury-02',
    description:
          'Discover bold style with the Phenomenal Mercury-02 sunglasses by Persol. Designed for those who appreciate both fashion and function, these sunglasses offer a unique design that stands out. The high-quality materials and precise construction ensure comfort and lasting quality. Elevate your style with these stylish and functional sunglasses.',
    brand: 'Persol',
    category: 'Sunglasses',
    gender: 'Unisex',
    weight: '100g',
    quantity: 5,
    image: 'sun4',
    rating: 2.8,
    price: 1299,
    newPrice: 1200,
  },
  {
    _id: '61bf1558-94c3-4494-a522-0aad46ed5334',
    qty: 0,
    name: 'Black boss',
    description:
          'Experience sophistication and style with the Black Boss sunglasses by Kate Spade. Designed for those who appreciate both fashion and function, these sunglasses offer a versatile design that complements any look. The high-quality materials and precise construction ensure comfort and lasting quality. Elevate your style with these stylish and functional sunglasses.',
    brand: 'Kate Spade',
    category: 'Sunglasses',
    gender: 'Unisex',
    weight: '750g',
    quantity: 15,
    image: 'sun5',
    rating: 4.7,
    price: 2999,
    newPrice: 2399,
    trending: true,
  },
  {
    _id: 'a2e6f1b8-d81c-4d1a-bc58-8be6a2e29f67',
    qty: 20,
    name: 'Elegance Frames',
    description:
          'Experience sophistication and elegance with the Elegance Frames sunglasses by ChicAura. Designed for those who appreciate refined aesthetics, these sunglasses feature a sleek and timeless design that complements any outfit. The premium materials ensure durability and comfort, while the lenses provide reliable UV protection. Elevate your style with these stylish and versatile sunglasses.',
    brand: 'ChicAura',
    category: 'Sunglasses',
    gender: 'Women',
    weight: '110g',
    quantity: 30,
    image: 'sun6',
    rating: 4.7,
    price: 3299,
    newPrice: 2799,
    trending: true,
  },
  {
    _id: 'c39a126c-783e-4926-bedd-0b2174307d9c',
    qty: 0,
    name: 'Pernik',
    description:
          'Step into style and versatility with the Pernik sunglasses by Carrera. Designed for those who appreciate both fashion and function, these sunglasses offer a modern and sleek design that complements any look. The high-quality materials and precise construction ensure comfort and lasting quality. Elevate your style with these versatile and fashionable sunglasses.',
    brand: 'Carrera',
    category: 'Sunglasses',
    gender: 'Unisex',
    weight: '300g',
    quantity: 8,
    image: 'sun7',
    rating: 3.8,
    price: 2499,
    newPrice: 1599,
  },
  {
    _id: '2e792ac4-13a7-4d70-a9a5-55294e346404',
    qty: 0,
    name: 'Silistra',
    description:
          'Step into elegance and sophistication with the Silistra sunglasses by Oakley. Designed for the modern woman who values both style and vision, these sunglasses offer a timeless and versatile look that complements any outfit. The high-quality materials and precise construction ensure comfort and lasting quality. Elevate your style with these exquisite and fashionable sunglasses.',
    brand: 'Oakley',
    category: 'Sunglasses',
    gender: 'Women',
    weight: '900g',
    quantity: 3,
    image: 'sun8',
    rating: 3.5,
    price: 3999,
    newPrice: 3599,
  },
  {
    _id: '1c9bd0c1-b300-4358-9eb4-43a70e392859',
    qty: 0,
    name: 'Ruse',
    description:
          'Elevate your style with the Ruse sunglasses by Kate Spade. Designed for the modern man who values both fashion and function, these sunglasses offer a classic and versatile design that complements any look. The high-quality materials and precision construction ensure comfort and lasting quality. Elevate your style with these stylish and functional sunglasses.',
    brand: 'Kate Spade',
    category: 'Sunglasses',
    gender: 'Men',
    weight: '400g',
    quantity: 6,
    image: 'sun9',
    rating: 4.1,
    price: 1499,
    newPrice: 1350,
  },
  {
    _id: '08617c37-e290-4296-b558-2db509201361',
    qty: 0,
    name: 'Yambol',
    description:
          'Discover bold style with the Yambol sunglasses by Ray-Ban. Designed for those who appreciate both fashion and function, these sunglasses offer a unique design that stands out. The high-quality materials and precise construction ensure comfort and lasting quality. Elevate your style with these stylish and functional sunglasses.',
    brand: 'Ray-Ban',
    category: 'Sunglasses',
    gender: 'Men',
    weight: '130g',
    quantity: 9,
    image: 'sun10',
    rating: 4.3,
    price: 2999,
    newPrice: 1999,
  },
  {
    _id: 'bb2ad041-b53a-49a8-835d-e84300e6fbd2',
    qty: 0,
    name: 'Griffith',
    description:
          'Step into style and versatility with the Griffith sunglasses by Carrera. Designed for those who appreciate both fashion and function, these sunglasses offer a modern and sleek design that complements any look. The high-quality materials and precise construction ensure comfort and lasting quality. Elevate your style with these versatile and fashionable sunglasses.',
    brand: 'Carrera',
    category: 'Sunglasses',
    gender: 'Women',
    weight: '550g',
    quantity: 7,
    image: 'sun11',
    rating: 4.8,
    price: 4999,
    newPrice: 4000,
  },
  {
    _id: 'a0a1ca71-d121-48af-a463-4ee790df28de',
    qty: 0,
    name: 'Sofia',
    description:
          'Experience sophistication and style with the Sofia sunglasses by Carrera. Designed for those who appreciate both fashion and function, these sunglasses offer a versatile design that complements any look. The high-quality materials and precise construction ensure comfort and lasting quality. Elevate your style with these stylish and functional sunglasses.',
    brand: 'Carrera',
    category: 'Sunglasses',
    gender: 'Women',
    weight: '550g',
    quantity: 7,
    image: 'sun12',
    rating: 4.8,
    price: 4999,
    newPrice: 4399,
  },
  {
    _id: '2b5f4f03-7ec7-4a5c-b2a7-14dbcc4f2f6b',
    qty: 0,
    name: 'Plovediv',
    description:
          'Step into style and versatility with the Plovediv sunglasses by Carrera. Designed for those who appreciate both fashion and function, these sunglasses offer a modern and sleek design that complements any look. The high-quality materials and precise construction ensure comfort and lasting quality. Elevate your style with these versatile and fashionable sunglasses.',
    brand: 'Carrera',
    category: 'Sunglasses',
    gender: 'Unisex',
    weight: '550g',
    quantity: 7,
    image: 'sun13',
    rating: 4.8,
    price: 4999,
    newPrice: 3499,
  },
  {
    _id: '5f73b408-aa98-4f54-a15b-7a7425a038d5',
    qty: 0,
    name: 'Roadies Rd-202',
    description:
          'Step into style and versatility with the Roadies Rd-202 sunglasses by Carrera. Designed for those who appreciate both fashion and function, these sunglasses offer a modern and sleek design that complements any look. The high-quality materials and precise construction ensure comfort and lasting quality. Elevate your style with these versatile and fashionable sunglasses.',
    brand: 'Carrera',
    category: 'Sunglasses',
    gender: 'Men',
    weight: '550g',
    quantity: 7,
    image: 'sun14',
    rating: 4.8,
    price: 4999,
    newPrice: 4799,
  },
];
const imageUrls = [
  'https://firebasestorage.googleapis.com/v0/b/visionpro-auth.appspot.com/o/products%2Fsports1.png?alt=media&token=9c0b47c0-463b-4c65-bf4d-a01b2215d339',
  'https://firebasestorage.googleapis.com/v0/b/visionpro-auth.appspot.com/o/products%2Fsports2.png?alt=media&token=ea7b034e-1812-4542-9f91-a632ab2443d0',
  'https://firebasestorage.googleapis.com/v0/b/visionpro-auth.appspot.com/o/products%2Fsports3.png?alt=media&token=f6c4d351-bed9-468c-99fd-b28f690c9d98',
  'https://firebasestorage.googleapis.com/v0/b/visionpro-auth.appspot.com/o/products%2Fsports4.png?alt=media&token=6bbd9530-7bee-4002-92e7-33d8b489679b',
  'https://firebasestorage.googleapis.com/v0/b/visionpro-auth.appspot.com/o/products%2Fsports5.png?alt=media&token=7bb96bd8-6a62-4c17-bf25-a0c7b07a9dab',
  'https://firebasestorage.googleapis.com/v0/b/visionpro-auth.appspot.com/o/products%2Fsports6.png?alt=media&token=93b8982f-565b-4d7e-97ca-ac0fd8156240',
  'https://firebasestorage.googleapis.com/v0/b/visionpro-auth.appspot.com/o/products%2Fsports7.png?alt=media&token=c61be50e-e5ad-433a-be09-a3da9ccf8781',
  'https://firebasestorage.googleapis.com/v0/b/visionpro-auth.appspot.com/o/products%2Fsports8.png?alt=media&token=17b01257-c1b8-4392-b31f-f3ed494cb341',
  'https://firebasestorage.googleapis.com/v0/b/visionpro-auth.appspot.com/o/products%2Fsports9.png?alt=media&token=5a7bda6c-fec6-4fd8-ba91-995660831889',
  'https://firebasestorage.googleapis.com/v0/b/visionpro-auth.appspot.com/o/products%2Fvision1.png?alt=media&token=f7e96961-fbff-4822-a3dd-d2353af7b2bb',
  'https://firebasestorage.googleapis.com/v0/b/visionpro-auth.appspot.com/o/products%2Fvision2.png?alt=media&token=6ed7f2bc-9b07-483b-bd1b-8bcd14c41f5b',
  'https://firebasestorage.googleapis.com/v0/b/visionpro-auth.appspot.com/o/products%2Fvision3.png?alt=media&token=6fde660c-4a33-424d-be91-f0af4a921673',
  'https://firebasestorage.googleapis.com/v0/b/visionpro-auth.appspot.com/o/products%2Fvision4.png?alt=media&token=e524d844-bd75-46a4-9985-790b9649d59e',
  'https://firebasestorage.googleapis.com/v0/b/visionpro-auth.appspot.com/o/products%2Fvision5.png?alt=media&token=376f6b6f-60f0-43f1-be0d-875268ab48ba',
  'https://firebasestorage.googleapis.com/v0/b/visionpro-auth.appspot.com/o/products%2Fvision6.png?alt=media&token=27c9b38d-f7a0-4561-aba6-5e402892cd52',
  'https://firebasestorage.googleapis.com/v0/b/visionpro-auth.appspot.com/o/products%2Fvision7.png?alt=media&token=b137cedf-2afb-4170-8498-7f6810cc620d',
  'https://firebasestorage.googleapis.com/v0/b/visionpro-auth.appspot.com/o/products%2Fvision8.png?alt=media&token=da1f400d-b2d2-48ff-9691-f207e8bb600a',
  'https://firebasestorage.googleapis.com/v0/b/visionpro-auth.appspot.com/o/products%2Fvision9.png?alt=media&token=cddea6bb-75e9-4b36-8f07-f0653b1c8ca7',
  'https://firebasestorage.googleapis.com/v0/b/visionpro-auth.appspot.com/o/products%2Fzsun1.png?alt=media&token=45dc7642-2c9f-4c47-a1e9-b19009f710ae',
  'https://firebasestorage.googleapis.com/v0/b/visionpro-auth.appspot.com/o/products%2Fzsun2.png?alt=media&token=17efcc30-5fe1-403c-8041-67d8e5c4ec06',
  'https://firebasestorage.googleapis.com/v0/b/visionpro-auth.appspot.com/o/products%2Fzsun3.png?alt=media&token=fc2d505b-9b49-40b1-923e-3fd5b8e6ffdf',
  'https://firebasestorage.googleapis.com/v0/b/visionpro-auth.appspot.com/o/products%2Fzsun4.png?alt=media&token=2356fdc9-dca4-4af2-b50d-c5e02d12f69a',
  'https://firebasestorage.googleapis.com/v0/b/visionpro-auth.appspot.com/o/products%2Fzsun5.png?alt=media&token=58a9f97a-826e-4ea7-b864-fe151288fc16',
  'https://firebasestorage.googleapis.com/v0/b/visionpro-auth.appspot.com/o/products%2Fzsun6.png?alt=media&token=df52d6c9-bf05-49ee-a1e5-530b1422f16b',
  'https://firebasestorage.googleapis.com/v0/b/visionpro-auth.appspot.com/o/products%2Fzsun7.png?alt=media&token=b8fd315d-bc3e-4a0d-b149-6df785cfa1a5',
  'https//firebasestorage.googleapis.com/v0/b/visionpro-auth.appspot.com/o/products%2Fzsun8.png?alt=media&token=246a427a-c2ef-46a0-8caa-62a82e25189d',
  'https://firebasestorage.googleapis.com/v0/b/visionpro-auth.appspot.com/o/products%2Fzsun9.png?alt=media&token=253a6015-ee6b-4423-92ed-3e40462d1e1d',
  'https://firebasestorage.googleapis.com/v0/b/visionpro-auth.appspot.com/o/products%2Fzzsun10.png?alt=media&token=9b9a249c-0cd2-43c5-970f-27e6e13f382d',
  'https://firebasestorage.googleapis.com/v0/b/visionpro-auth.appspot.com/o/products%2Fzzsun11.png?alt=media&token=3e7dc2a8-5c37-43a7-938c-af62d9b73e79',
  'https://firebasestorage.googleapis.com/v0/b/visionpro-auth.appspot.com/o/products%2Fzzsun12.png?alt=media&token=9979ccb3-ea8f-4f8e-ae05-dbba258ef12b',
  'https://firebasestorage.googleapis.com/v0/b/visionpro-auth.appspot.com/o/products%2Fzzsun13.png?alt=media&token=3c6bac8c-43b9-4b43-8825-d8b92e93b388',
  'https://firebasestorage.googleapis.com/v0/b/visionpro-auth.appspot.com/o/products%2Fzzsun14.png?alt=media&token=d776b974-754d-4636-ab70-1f9024721f53',
];
for (let i = 0; i < products.length; i++) {
  products[i].image = imageUrls[i];
}
console.log(products);
console.log(products.length);
console.log(products[9]);
