export const popularProducts = [
  {
    id: 'fcd7e3a2-80f9-47d1-9e34-6a40e5f684a1',
    qty: 15,
    name: 'Athletic Shades',
    description: 'Gear up for intense outdoor activities with the Athletic Shades sunglasses by SportX. Engineered for performance, these shades provide optimal UV protection and enhanced clarity. The lightweight and durable design ensures they stay put during your most rigorous adventures. Elevate your sports experience with these high-performance sunglasses.',
    brand: 'SportX',
    category: 'Sunglasses',
    gender: 'Unisex',
    weight: '90g',
    quantity: 25,
    image: 'https://firebasestorage.googleapis.com/v0/b/visionpro-auth.appspot.com/o/products%2Fsports5.png?alt=media&token=7bb96bd8-6a62-4c17-bf25-a0c7b07a9dab',
    rating: 4.9,
    price: 2499,
    newPrice: 1999,
    trending: true,
  }, {
    id: '887cdd99-1503-4527-aef4-88c521126a47',
    qty: 0,
    name: 'Caper Active',
    description: 'Elevate your active lifestyle with the Caper Active sunglasses from Persol. Designed for the modern man who embraces challenges, these shades provide a sporty edge that complements any adventure. The lightweight build and UV protection make them a reliable choice for outdoor enthusiasts. Embrace the Persol brand and enhance your sports gear with these Active sunglasses.',
    brand: 'Persol',
    category: 'Sports',
    gender: 'Men',
    weight: '100g',
    quantity: 5,
    image: 'https://firebasestorage.googleapis.com/v0/b/visionpro-auth.appspot.com/o/products%2Fsports2.png?alt=media&token=ea7b034e-1812-4542-9f91-a632ab2443d0',
    rating: 4.8,
    price: 1299,
    newPrice: 1199,
    trending: true,
  }, {
    id: '9e3419eb-e5f6-4813-8bf4-6d72b6498235',
    qty: 0,
    name: 'Blue Ray Wayfarer',
    description: 'Experience timeless elegance with the Blue Ray Wayfarer sunglasses by Carrera. Designed for those who appreciate unisex fashion, these shades offer a blend of sophistication and style. The high-quality materials ensure durability and comfort, while the lenses provide optimal UV protection. Elevate your look with these exquisite sunglasses that exude charm and grace.',
    brand: 'Carrera',
    category: 'Sports',
    gender: 'Unisex',
    weight: '550g',
    quantity: 7,
    image: 'https://firebasestorage.googleapis.com/v0/b/visionpro-auth.appspot.com/o/products%2Fsports9.png?alt=media&token=5a7bda6c-fec6-4fd8-ba91-995660831889',
    rating: 4.8,
    price: 4999,
    newPrice: 4000,
  },
  {
    id: 'ac072970-8dac-42fe-8c31-a8fa6fd4b64a',
    qty: 0,
    name: 'Full Rim Airflex',
    description: 'Elevate your optical experience with the Full Rim Airflex glasses by Carrera. Designed for those who appreciate both style and function, these glasses offer a blend of modern design and reliable vision. The high-quality materials and precision construction ensure comfort and lasting quality. Elevate your vision with these versatile and fashionable glasses.',
    brand: 'Carrera',
    category: 'Vision',
    gender: 'Unisex',
    weight: '550g',
    quantity: 7,
    image: 'https://firebasestorage.googleapis.com/v0/b/visionpro-auth.appspot.com/o/products%2Fvision8.png?alt=media&token=da1f400d-b2d2-48ff-9691-f207e8bb600a',
    rating: 4.8,
    price: 4999,
    newPrice: 3999,
  },
  {
    id: '8ad38385-1211-4192-8108-db851b4e9434',
    qty: 0,
    name: 'Mercury Rounded Red',
    description: 'Step into sophistication with the Mercury Rounded Red glasses by Carrera. Designed for the contemporary individual who values both style and vision, these glasses offer a unique rounded shape thats perfect for any occasion. The high-quality materials and precision construction ensure comfort and lasting quality. Elevate your vision with these versatile and stylish glasses.',
    brand: 'Carrera',
    category: 'Vision',
    gender: 'Unisex',
    weight: '550g',
    quantity: 7,
    image: 'https://firebasestorage.googleapis.com/v0/b/visionpro-auth.appspot.com/o/products%2Fvision9.png?alt=media&token=cddea6bb-75e9-4b36-8f07-f0653b1c8ca7',
    rating: 4.8,
    price: 4999,
  }, {
    id: '53ca5f50-39f4-4c77-be14-c3246cfc5dc6',
    qty: 0,
    name: 'Burgas',
    description: 'Step into elegance and sophistication with the Burgas sunglasses by Carrera. Designed for the modern woman who values both style and vision, these sunglasses offer a timeless and versatile look that complements any outfit. The high-quality materials and precise construction ensure comfort and lasting quality. Elevate your style with these exquisite and fashionable sunglasses.',
    brand: 'Carrera',
    category: 'Sunglasses',
    gender: 'Women',
    weight: '550g',
    quantity: 7,
    image: 'https://firebasestorage.googleapis.com/v0/b/visionpro-auth.appspot.com/o/products%2Fzsun2.png?alt=media&token=17efcc30-5fe1-403c-8041-67d8e5c4ec06',
    rating: 4.8,
    price: 4999,
    newPrice: 4700,
  }, {
    id: 'bb2ad041-b53a-49a8-835d-e84300e6fbd2',
    qty: 0,
    name: 'Griffith',
    description: 'Step into style and versatility with the Griffith sunglasses by Carrera. Designed for those who appreciate both fashion and function, these sunglasses offer a modern and sleek design that complements any look. The high-quality materials and precise construction ensure comfort and lasting quality. Elevate your style with these versatile and fashionable sunglasses.',
    brand: 'Carrera',
    category: 'Sunglasses',
    gender: 'Women',
    weight: '550g',
    quantity: 7,
    image: 'https://firebasestorage.googleapis.com/v0/b/visionpro-auth.appspot.com/o/products%2Fzzsun11.png?alt=media&token=3e7dc2a8-5c37-43a7-938c-af62d9b73e79',
    rating: 4.8,
    price: 4999,
    newPrice: 4000,
  },
]